services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/thysecser.egg-info
    image: ghcr.io/informatica-na-presales-ops/thysecser-dev
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile:py3.12
    image: ghcr.io/williamjacksn/pip-tools
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/informatica-na-presales-ops/thysecser-dev
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/thysecser-dev
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api
