services:
  pip-compile:
    entrypoint:
      - /bin/sh
      - -c
      - pip install pip-tools && pip-compile
    image: ghcr.io/informatica-na-presales-ops/thycotic-secret-server-api
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/thycotic-secret-server-api
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  sync-ops-web-passwords:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/thycotic-secret-server-api/sync-ops-web-passwords.py
    environment:
      DB: (set in compose.override.yaml)
      SECRET_SERVER_FOLDER_ID: (set in compose.override.yaml)
      SECRET_SERVER_HOSTNAME: (set in compose.override.yaml)
      SECRET_SERVER_PASSWORD: (set in compose.override.yaml)
      SECRET_SERVER_SITE_ID: (set in compose.override.yaml)
      SECRET_SERVER_TEMPLATE_ID: (set in compose.override.yaml)
      SECRET_SERVER_USERNAME: (set in compose.override.yaml)
    image: ghcr.io/informatica-na-presales-ops/thycotic-secret-server-api
    init: true
