### token
POST https://{{host}}/SecretServer/oauth2/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type = password &
username = {{username}} &
password = {{password}}

> {% client.global.set('token', response.body['access_token']); %}

### lookup-folders
GET https://{{host}}/SecretServer/api/v1/folders/lookup
    ?filter.searchText=machine-credentials
Authorization: Bearer {{token}}

### get-template
GET https://{{host}}/SecretServer/api/v1/secret-templates/{{secret_template_id}}
Authorization: Bearer {{token}}

### list-secrets
GET https://{{host}}/SecretServer/api/v2/secrets
    ?filter.folderId={{folder_id}}
#    ?filter.searchText={{secret_name}}
#    ?take=100
#    ?skip=170
Authorization: Bearer {{token}}

### lookup-secrets
GET https://{{host}}/SecretServer/api/v1/secrets/lookup
Authorization: Bearer {{token}}

### get-secret
GET https://{{host}}/SecretServer/api/v2/secrets/{{secret_id}}
Authorization: Bearer {{token}}

### post-secret
POST https://{{host}}/SecretServer/api/v1/secrets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siteId": {{site_id}},
  "folderId": {{folder_id}},
  "items": [
    {
      "fieldId": {{secret_username_field_id}},
      "itemValue": "{{secret_username}}"
    },
    {
      "fieldId": {{secret_password_field_id}},
      "itemValue": "{{secret_password}}"
    }
  ],
  "name": "{{secret_name}}",
  "secretTemplateId": {{secret_template_id}}
}

### put-secret
PUT https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siteId": {{site_id}},
  "id": {{secret_id}},
  "items": [],
  "name": "{{secret_name}}"
}

### delete-secret
DELETE https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}

### generate-password
POST https://{{host}}/SecretServer/api/v1/secret-templates/generate-password/{{secret_password_field_id}}
Authorization: Bearer {{token}}
