###

POST https://{{host}}/SecretServer/oauth2/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&grant_type=password

> {% client.global.set('token', response.body['access_token']); %}

###

GET https://{{host}}/SecretServer/api/v1/folders/lookup
    ?filter.searchText=machine-credentials
Authorization: Bearer {{token}}

###

GET https://{{host}}/SecretServer/api/v1/secret-templates/{{secret_template_id}}
Authorization: Bearer {{token}}

###

GET https://{{host}}/SecretServer/api/v1/secrets
#    ?filter.folderId={{folder_id}}
#    ?take=100
#    ?skip=170
Authorization: Bearer {{token}}

###

GET https://{{host}}/SecretServer/api/v1/secrets/lookup
Authorization: Bearer {{token}}

###

GET https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}

###

POST https://{{host}}/SecretServer/api/v1/secrets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siteId": {{site_id}},
  "folderId": {{folder_id}},
  "items": [
    {
      "fieldId": {{secret_username_field_id}},
      "itemValue": "{{secret_username}}"
    },
    {
      "fieldId": {{secret_password_field_id}},
      "itemValue": "{{secret_password}}"
    }
  ],
  "name": "{{secret_name}}",
  "secretTemplateId": {{secret_template_id}}
}

###

PUT https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siteId": {{site_id}},
  "id": {{secret_id}},
  "items": [],
  "name": "{{secret_name}}"
}

###

DELETE https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}

###
