###

POST https://{{host}}/SecretServer/oauth2/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&grant_type=password

> {% client.global.set('token', response.body.access_token); %}

###

GET https://{{host}}/SecretServer/api/v1/secrets
    ?filter.folderId={{folder_id}}
Authorization: Bearer {{token}}

###

GET https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}

###

POST https://{{host}}/SecretServer/api/v1/secrets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "siteId": {{site_id}},
  "folderId": {{folder_id}},
  "items": [
    {
      "fieldId": {{secret_username_field_id}},
      "itemValue": "{{secret_username}}"
    },
    {
      "fieldId": {{secret_password_field_id}},
      "itemValue": "{{secret_password}}"
    }
  ],
  "name": "{{secret_name}}",
  "secretTemplateId": {{secret_template_id}}
}

###

DELETE https://{{host}}/SecretServer/api/v1/secrets/{{secret_id}}
Authorization: Bearer {{token}}

###
