name: Build the container image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_image:
        description: Push latest image
        required: true
        type: boolean

env:
  image_name: ghcr.io/informatica-na-presales-ops/thysecser-dev

jobs:

  build:
    name: Build the helper image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.image_name }}:latest

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push_image)
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push_image)
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          push: true
          tags: ${{ env.image_name }}:latest
