name: Publish the release package to PyPI

on:
  release:
    types:
      - published

jobs:

  publish:
    name: Publish the release package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/p/thysecser
    permissions:
      id-token: write
    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build the package
        run: docker compose run --user "$(id -u):$(id -g)" --no-TTY py-build

      - name: Publish the package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
